<?xml version="1.0"?>
<robot name="custom_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Include sensor macros -->
  <xacro:include filename="$(find custom_robot_description)/urdf/sensors/velodyne.urdf.xacro"/>
  <xacro:include filename="$(find custom_robot_description)/urdf/sensors/imu.urdf.xacro"/>
  
  <!-- Robot Properties -->
  <xacro:property name="chassis_length" value="0.6"/>
  <xacro:property name="chassis_width" value="0.4"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_mass" value="15.0"/>
  
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_mass" value="1.0"/>
  
  <!-- Base Footprint (for TF tree) -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Main Chassis -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.3 0.8 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="prefix side reflect">
    <link name="${prefix}_${side}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_${side}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_${side}_wheel"/>
      <origin xyz="${reflect * 0.2} ${reflect * 0.25} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Create 4 Wheels -->
  <xacro:wheel prefix="front" side="left" reflect="1"/>
  <xacro:wheel prefix="front" side="right" reflect="-1"/>
  <xacro:wheel prefix="rear" side="left" reflect="1"/>
  <xacro:wheel prefix="rear" side="right" reflect="-1"/>

  <!-- Include Sensors -->
  <xacro:velodyne_sensor parent="base_link">
    <origin xyz="0.0 0.0 ${chassis_height/2 + 0.1}" rpy="0 0 0"/>
  </xacro:velodyne_sensor>

  <xacro:imu_sensor parent="base_link">
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </xacro:imu_sensor>

    <!-- Differential Drive Plugin -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <update_rate>50</update_rate>
      
      <!-- Wheel joints -->
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      
      <!-- Wheel parameters -->
      <wheel_separation>0.5</wheel_separation>
      <wheel_diameter>0.2</wheel_diameter>
      
      <!-- Limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      
      <!-- Command topic -->
      <command_topic>cmd_vel</command_topic>
      
      <!-- Odometry -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

</robot>