<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="husky">

  <!-- Properties -->
  <xacro:property name="M_PI" value="3.14159265359"/>
  
  <!-- Base dimensions -->
  <xacro:property name="base_x_size" value="0.98740000" />
  <xacro:property name="base_y_size" value="0.57090000" />
  <xacro:property name="base_z_size" value="0.24750000" />
  
  <!-- Wheel properties -->
  <xacro:property name="wheelbase" value="0.5120" />
  <xacro:property name="track" value="0.555" />
  <xacro:property name="wheel_vertical_offset" value="0.03282" />
  <xacro:property name="wheel_length" value="0.1143" />
  <xacro:property name="wheel_radius" value="0.1651" />
  <xacro:property name="wheel_mass" value="2.0" />

  <!-- Include sensor macros -->
  <xacro:include filename="$(find husky_minimal)/urdf/sensors/imu.urdf.xacro"/>
  <xacro:include filename="$(find husky_minimal)/urdf/sensors/velodyne.urdf.xacro"/>
  
  <!-- Top Chassis -->
  <link name="top_chassis_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/top_chassis.dae" />
      </geometry>
    </visual>
  </link>

  <joint name="top_chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="top_chassis_link" />
  </joint>

  <!-- Front Bumper -->
  <link name="front_bumper_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/bumper.dae" />
      </geometry>
    </visual>
  </link>

  <joint name="front_bumper_joint" type="fixed">
    <origin xyz="0.48 0 0.091" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="front_bumper_link" />
  </joint>

  <!-- Rear Bumper -->
  <link name="rear_bumper_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/bumper.dae" />
      </geometry>
    </visual>
  </link>

  <joint name="rear_bumper_joint" type="fixed">
    <origin xyz="-0.48 0 0.091" rpy="0 0 3.14159" />
    <parent link="base_link" />
    <child link="rear_bumper_link" />
  </joint>

  <!-- User Rail -->
  <link name="user_rail_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/user_rail.dae" />
      </geometry>
    </visual>
  </link>

  <joint name="user_rail_joint" type="fixed">
    <origin xyz="0.272 0 0.245" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="user_rail_link" />
  </joint>

  <!-- Top Plate -->
  <link name="top_plate_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/top_plate.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/top_plate.stl" />
      </geometry>
    </collision>
  </link>

  <joint name="top_plate_joint" type="fixed">
    <parent link="base_link" />
    <child link="top_plate_link"/>
    <origin xyz="0.0812 0 0.245" rpy="0 0 0"/>
  </joint>

  <!-- Top Plate Front Link -->
  <link name="top_plate_front_link"/>
  
  <joint name="top_plate_front_joint" type="fixed">
    <parent link="top_plate_link" />
    <child link="top_plate_front_link"/>
    <origin xyz="0.36367 0 0.00639" rpy="0 0 0"/>
  </joint>

  <!-- Top Plate Rear Link -->
  <link name="top_plate_rear_link"/>
  
  <joint name="top_plate_rear_joint" type="fixed">
    <parent link="top_plate_link" />
    <child link="top_plate_rear_link"/>
    <origin xyz="-0.36633 0 0.00639" rpy="0 0 0"/>
  </joint>


  <!-- IMU Sensor -->
  <xacro:imu_sensor parent="base_link">
    <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
  </xacro:imu_sensor>

  <!-- Velodyne LiDAR -->
  <xacro:velodyne_sensor parent="top_plate_link">
    <origin xyz="0.0 0.0 0.1" rpy="0 0 0"/>
  </xacro:velodyne_sensor>



  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="file://$(find husky_minimal)/meshes/base_link.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_z_size/4}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size/2}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="46.034" />
      <origin xyz="-0.00065 -0.085 0.062" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" 
               iyy="1.7386" iyz="-0.001544" izz="2.0296" />
    </inertial>
  </link>

  <!-- Base footprint -->
  <link name="base_footprint"/>
  
  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find husky_minimal)/meshes/wheel.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.0246688" ixy="0" ixz="0"
                 iyy="0.0246688" iyz="0" izz="0.0441058"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 ${reflect * track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
    </gazebo>
  </xacro:macro>

  <!-- Front wheels -->
  <xacro:macro name="front_wheel" params="prefix reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find husky_minimal)/meshes/wheel.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.0246688" ixy="0" ixz="0"
                 iyy="0.0246688" iyz="0" izz="0.0441058"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${wheelbase/2} ${reflect * track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
    </gazebo>
  </xacro:macro>

  <!-- Rear wheels -->
  <xacro:macro name="rear_wheel" params="prefix reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find husky_minimal)/meshes/wheel.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.0246688" ixy="0" ixz="0"
                 iyy="0.0246688" iyz="0" izz="0.0441058"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${-wheelbase/2} ${reflect * track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
    </gazebo>
  </xacro:macro>

  <!-- Instantiate wheels -->
  <xacro:front_wheel prefix="front_left" reflect="1"/>
  <xacro:front_wheel prefix="front_right" reflect="-1"/>
  <xacro:rear_wheel prefix="rear_left" reflect="1"/>
  <xacro:rear_wheel prefix="rear_right" reflect="-1"/>

  <!-- ROS2 Control -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    
    <joint name="front_left_wheel">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="front_right_wheel">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="rear_left_wheel">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <joint name="rear_right_wheel">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo ROS2 Control Plugin -->
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>$(find husky_minimal)/config/husky_controllers.yaml</parameters>
    </plugin>
</gazebo>

</robot>
